# customer-service.yml (in Config Server's Git Repository)

server:
  port: 9091 # The port for this service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb?createDatabaseIfNotExist=true
    username: root
    password: team03
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
